framework:
    workflows:
        comment:
            type: state_machine
            audit_trail:
                enabled: "%kernel.debug%"
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Advert
            initial_marking: draft
            places:
                - draft
                - rejected
                - published
            transitions:
                accept:
                    from: draft
                    to:   published
                reject:
                    from: draft
                    to:   rejected
                reject_accepted:
                    from: published
                    to: rejected